# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

name: Build and Test Pull Request

on:
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true
      
      - name: Lint
        run: go get -u golang.org/x/lint/golint || true
    
      - name: Imports
        run: go get golang.org/x/tools/cmd/goimports
    
      - name: UsedExports
        run: go get github.com/jgautheron/usedexports
    
      - name: ErrorCheck
        run: go get -u github.com/kisielk/errcheck
    
      - name: Check
        run: make check
    
      - name: Test
        run: make test
    
      - name: Test-Coverage
        run: make test-coverage
    
      - name: Build
        run: make build
